name: EvaFi Playwright Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  playwright-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create virtual environment
        run: |
          python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          source venv/bin/activate
          playwright install --with-deps

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: evafi-test-reports
          path: reports/